/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_appsync_graphqlEndpoint": "https://d5zjdm7pl5h5vn2uwlxvzkldia.appsync-api.sa-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "sa-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-j3ppbjkjmrcu5i3zccwpotaexe",
    "aws_cloud_logic_custom": [
        {
            "name": "textractapi",
            "endpoint": "https://5div9f7zai.execute-api.sa-east-1.amazonaws.com/prod",
            "region": "sa-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "sa-east-1:c754b8b0-a97a-44a7-812d-fb987a2e909b",
    "aws_cognito_region": "sa-east-1",
    "aws_user_pools_id": "sa-east-1_BB4whgkNy",
    "aws_user_pools_web_client_id": "67nd6675qo1u04v63trbutnfte",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "s3-packflowstorage87346-prod",
    "aws_user_files_s3_bucket_region": "sa-east-1"
};


export default awsmobile;
